import React, { useState } from "react";
import Header from "../../components/Layout/Header";
import Footer from "../../components/Layout/Footer";

const ImageGenerationPage = () => {
  const [prompt, setPrompt] = useState("");
  const [imageUrl, setImageUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleGenerateImage = async () => {
    if (!prompt.trim()) {
      setError("Please provide a valid prompt.");
      return;
    }
  
    setLoading(true);
    setError("");
  
    try {
      const response = await fetch("http://localhost:8000/api/aiml/generate-image", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ prompt }),
      });
  
      if (!response.ok) {
        throw new Error("Failed to generate image.");
      }
  
      const data = await response.json();
      setImageUrl(data.imageUrl);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };
  return (
    <div className="bg-gray-100 min-h-screen">
      <Header />

      {/* Hero Section */}
      <section className="bg-gradient-to-r from-purple-600 to-indigo-600 text-white py-16 text-center">
        <h1 className="text-4xl font-bold">AI Image Generator</h1>
        <p className="mt-4">Generate amazing images using AI technology.</p>
      </section>

      {/* Image Generation Section */}
      <section className="py-16 px-4">
        <div className="container mx-auto">
          <div className="flex flex-col items-center">
            <textarea
              className="w-full max-w-2xl h-28 p-4 border border-gray-300 rounded-lg shadow-md resize-none focus:outline-none focus:ring-2 focus:ring-indigo-500"
              placeholder="Describe the image you want to generate..."
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
            ></textarea>
            <button
              className="mt-6 bg-indigo-500 hover:bg-indigo-600 text-white px-6 py-3 rounded-lg shadow-md"
              onClick={handleGenerateImage}
              disabled={loading}
            >
              {loading ? "Generating..." : "Generate Image"}
            </button>
            {error && <p className="text-red-500 mt-4">{error}</p>}
            {imageUrl && (
              <div className="mt-8">
                <img
                  src={imageUrl}
                  alt="Generated by AI"
                  className="max-w-md rounded-lg shadow-lg"
                />
              </div>
            )}
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default ImageGenerationPage;
